language: c++

sudo: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.5
    packages:
      - llvm-3.5
      - llvm-3.5-dev
      - clang-3.5
      - libedit-dev

script:
  - make
  # - make test
